### ISSUE TITLE
[BUG]: 북마크 추가 API가 정상적으로 동작하지 않습니다.

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#207]
## 관련 API

```md
[POST] /api/bookmarks
```

## 요청 Request

```json
{
    "url": "https://velog.io/@pyo-sh/React-Responsive",
    "title": "ㄴㄴ",
    "categoryId": 1,
    "visibility": "SCOPE_PUBLIC",
    "memberId": 1
}
```

## Spring log
```md
2023-07-23T04:34:44.902+09:00 ERROR 90113 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: jakarta.validation.ConstraintDefinitionException: HV000243: Constraint org.pickly.service.common.utils.validator.visibility.VisibilityCheck references constraint validator type org.pickly.service.common.utils.validator.url.UrlValidator, but this validator is defined for constraint type org.pickly.service.common.utils.validator.url.UrlCheck.] with root cause

jakarta.validation.ConstraintDefinitionException: HV000243: Constraint org.pickly.service.common.utils.validator.visibility.VisibilityCheck references constraint validator type org.pickly.service.common.utils.validator.url.UrlValidator, but this validator is defined for constraint type org.pickly.service.common.utils.validator.url.UrlCheck.
	at org.hibernate.validator.internal.engine.constraintvalidation.ClassBasedValidatorDescriptor.of(ClassBasedValidatorDescriptor.java:48) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintValidatorDescriptor.forClass(ConstraintValidatorDescriptor.java:49) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.lambda$getDefaultValidatorDescriptors$4(ConstraintHelper.java:1156) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.getDefaultValidatorDescriptors(ConstraintHelper.java:1157) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.lambda$getAllValidatorDescriptors$0(ConstraintHelper.java:879) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper$ValidatorDescriptorMap.computeIfAbsent(ConstraintHelper.java:1193) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.getAllValidatorDescriptors(ConstraintHelper.java:879) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.findValidatorDescriptors(ConstraintHelper.java:893) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.assertValidationAppliesToParameterSetUpCorrectly(ConstraintHelper.java:1072) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.lambda$isConstraintAnnotation$3(ConstraintHelper.java:1013) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.isConstraintAnnotation(ConstraintHelper.java:1009) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findConstraintAnnotations(AnnotationMetaDataProvider.java:534) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findConstraints(AnnotationMetaDataProvider.java:479) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findConstraints(AnnotationMetaDataProvider.java:461) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:236) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:229) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:130) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:121) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanConfigurationForHierarchy(BeanMetaDataManagerImpl.java:234) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.createBeanMetaData(BeanMetaDataManagerImpl.java:201) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.getBeanMetaData(BeanMetaDataManagerImpl.java:165) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:156) ~[hibernate-validator-8.0.0.Final.jar:8.0.0.Final]
```

**Comment by EunjiShin** [comment]
ㅋㅋㅋ아 얘 잘 돌아가다가 갑자기 왜이럴까요 😇😇 
확실히 기능이 많아질수록 충돌이 잦아지네요
테스트 코드를....꼼꼼히 작성하겠습니다.....

**Comment by EunjiShin** [comment]
일단 확인해보니 공개 범위 Visibility 체크를 타이틀에서 하고 있어서 문제가 된 것 같네요! 바로 수정할게요 
<img width="606" alt="스크린샷 2023-07-24 10 38 08" src="https://github.com/pickly-team/pickly-backend/assets/38103085/c1ad592c-fdb7-43ad-99c0-fa323dcb883c">
